### ISSUE TITLE
script errors in Unity 5.2.3p3

### ISSUE THREAD

**Issue by RYG81** [charlesveasey/FulldomeBootcamp#2]
Hi I am getting some errors on Unity 5.2.3p3
I have attached the image for the same
![errors](https://cloud.githubusercontent.com/assets/10570236/13106450/4de67d30-d58e-11e5-89d1-10b76720c437.png)

**Comment by charlesveasey** [comment]
Unfortunately, this project cannot be run on Unity 5.
